# Generated by Django 4.2.4 on 2023-09-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("idade", models.CharField(max_length=3)),
                ("email", models.EmailField(max_length=100)),
                ("telefone", models.CharField(max_length=13)),
                ("data_cadastro", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "Usuario",
            },
        ),
    ]
