# Generated by Django 4.2.4 on 2023-09-04 03:36

import app_cad_usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cad_usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="data_cadastro",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="idade",
            field=models.PositiveIntegerField(
                help_text="Informe a idade com no máximo 3 digitos.",
                validators=[app_cad_usuarios.models.validacao_max_digits],
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="nome",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="telefone",
            field=models.CharField(max_length=13),
        ),
    ]
