# Generated by Django 4.2.4 on 2023-09-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_cad_usuarios",
            "0002_alter_usuario_data_cadastro_alter_usuario_email_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="data_cadastro",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
